name: Build Pico2W Firmware

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake python3 wget xz-utils git ninja-build

      - name: Install ARM GCC Toolchain
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz
          tar -xf arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz
          TOOLCHAIN_DIR=$(pwd)/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi
          echo "TOOLCHAIN_DIR=$TOOLCHAIN_DIR" >> $GITHUB_ENV
          echo "$TOOLCHAIN_DIR/bin" >> $GITHUB_PATH
          arm-none-eabi-gcc --version || echo "ARM GCC not found"

      - name: Build mpy-cross
        run: |
          cd micropython/mpy-cross
          make -j$(nproc)

      - name: Build firmware for Pico W
        env:
          PICO_TOOLCHAIN_PATH: ${{ env.TOOLCHAIN_DIR }}
        run: |
          cd micropython/ports/rp2
          git submodule update --init --recursive
          cmake -DPICO_BOARD=pico_w -G "Ninja" .
          ninja

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: micropython-pico2w
          path: micropython/ports/rp2/build-PICO_W/firmware.uf2

