name: Build MicroPython for Pico 2 W

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout MicroPython
        uses: actions/checkout@v4
        with:
          repository: micropython/micropython
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential python3 python3-pip cmake git

      - name: Build mpy-cross
        run: |
          cd mpy-cross
          make -j$(nproc)

      - name: Build firmware for Pico 2 W
        run: |
          cd ports/rp2
          make submodules
          make BOARD=PICO2W -j$(nproc)

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: micropython-pico2w
          path: ports/rp2/build-PICO2W/firmware.uf2

