name: Build Pico W Firmware

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # --- 1. Checkout your repo and all submodules ---
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # --- 2. Install dependencies ---
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential ninja-build git

      # --- 3. Set up environment variables ---
      - name: Set up environment
        run: |
          echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/micropython/lib/pico-sdk" >> $GITHUB_ENV
          echo "PICO_BOARD=pico_w" >> $GITHUB_ENV

      # --- 4. Build MicroPython for Pico W ---
      - name: Build firmware
        run: |
          cd micropython
          make -C ports/rp2 submodules
          cd ports/rp2
          mkdir -p build-PICO_W
          cd build-PICO_W
          cmake .. -DPICO_BOARD=pico2_w -DPICO_SDK_PATH=$PICO_SDK_PATH -G "Ninja"
          ninja
          cd ../..
          echo "Firmware build finished!"

      # --- 5. Upload firmware artifact ---
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: pico_w_firmware
          path: micropython/ports/rp2/build-PICO_W/firmware.uf2

